kind: Deployment
apiVersion: apps/v1
metadata:
  name: edith-ui
  namespace: osficoe
  #  askid: UHGWM110-025917
  #  boundary: public
  #  owner: uhctech_cloudcoe_dev 
  labels:
    app: edith-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edith-ui
  template:
    metadata:
      labels:
        app: edith-ui
    spec:
      containers:
        - name: edith-ui
          image: 'docker.repo1.uhc.com/cloud-coe/edith-ui:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1500m
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 1Gi
      nodeName: ctc2hz1-04-s05.uhc.com
---
kind: Service
apiVersion: v1
metadata:
  name: edithui
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30020
  selector:
    app: edith-ui
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
